/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VehiclesVehicleIdIndexRouteImport } from './routes/vehicles.$vehicleId.index'
import { Route as VehiclesVehicleIdServiceLogsRouteImport } from './routes/vehicles.$vehicleId.service-logs'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesVehicleIdIndexRoute = VehiclesVehicleIdIndexRouteImport.update({
  id: '/vehicles/$vehicleId/',
  path: '/vehicles/$vehicleId/',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesVehicleIdServiceLogsRoute =
  VehiclesVehicleIdServiceLogsRouteImport.update({
    id: '/vehicles/$vehicleId/service-logs',
    path: '/vehicles/$vehicleId/service-logs',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/vehicles/$vehicleId/service-logs': typeof VehiclesVehicleIdServiceLogsRoute
  '/vehicles/$vehicleId/': typeof VehiclesVehicleIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/vehicles/$vehicleId/service-logs': typeof VehiclesVehicleIdServiceLogsRoute
  '/vehicles/$vehicleId': typeof VehiclesVehicleIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/vehicles/$vehicleId/service-logs': typeof VehiclesVehicleIdServiceLogsRoute
  '/vehicles/$vehicleId/': typeof VehiclesVehicleIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/vehicles/$vehicleId/service-logs' | '/vehicles/$vehicleId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/vehicles/$vehicleId/service-logs' | '/vehicles/$vehicleId'
  id:
    | '__root__'
    | '/'
    | '/vehicles/$vehicleId/service-logs'
    | '/vehicles/$vehicleId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VehiclesVehicleIdServiceLogsRoute: typeof VehiclesVehicleIdServiceLogsRoute
  VehiclesVehicleIdIndexRoute: typeof VehiclesVehicleIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles/$vehicleId/': {
      id: '/vehicles/$vehicleId/'
      path: '/vehicles/$vehicleId'
      fullPath: '/vehicles/$vehicleId/'
      preLoaderRoute: typeof VehiclesVehicleIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles/$vehicleId/service-logs': {
      id: '/vehicles/$vehicleId/service-logs'
      path: '/vehicles/$vehicleId/service-logs'
      fullPath: '/vehicles/$vehicleId/service-logs'
      preLoaderRoute: typeof VehiclesVehicleIdServiceLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VehiclesVehicleIdServiceLogsRoute: VehiclesVehicleIdServiceLogsRoute,
  VehiclesVehicleIdIndexRoute: VehiclesVehicleIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
